### ISSUE TITLE
free(): invalid pointer error in Grid destructor

### ISSUE THREAD

**Issue by connie-li** [connie-li/Battleship-2.0#18]
Menu:
 1) Start Game
 2) Instructions
 3) Quit Game

Enter option (1-3): 1

How many ships would you like to play with? (1-5 ships): 1
Player 1: It's time to place your ships.It's time to place your ship of size 1x1. Enter a starting coordinate
Please enter a coordinate in the form 1A: 1A
Thanks for placing your ships player 1! Now it's player 2's turnPlayer 2: It's time to place your ships.It's time to place your ship of size 1x1. Enter a starting coordinate
Please enter a coordinate in the form 1A: 1A
free(): invalid pointer

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7483801 in __GI_abort () at abort.c:79
#2  0x00007ffff74cc897 in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7ffff75f9b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff74d390a in malloc_printerr (str=str@entry=0x7ffff75f7d88 "free(): invalid pointer")
    at malloc.c:5350
#4  0x00007ffff74dae1c in _int_free (have_lock=0, p=0x555555771ef8, av=0x7ffff782ec40 <main_arena>)
    at malloc.c:4157
#5  __GI___libc_free (mem=0x555555771f08) at malloc.c:3124
#6  0x000055555555b5e9 in Grid::~Grid (this=0x555555771e70, __in_chrg=<optimized out>) at Grid.cpp:59
#7  0x000055555555983c in Admiral::~Admiral (this=0x555555771e70, __in_chrg=<optimized out>)
    at Admiral.cpp:17
#8  0x00005555555569c9 in Executive::~Executive (this=0x7fffffffe370, __in_chrg=<optimized out>)
    at Executive.cpp:13
#9  0x000055555555683b in main () at main.cpp:4

**Comment by connie-li** [comment]
Fixed: 2D array deletion in Grid destructor
