### ISSUE TITLE
seg fault in using a powerup

### ISSUE THREAD

**Issue by mschoeni179** [connie-li/Battleship-2.0#75]

**Comment by mschoeni179** [comment]
Player 1, would you like to use a powerup?

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b72d40 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7b72d40 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000055555555ea2e in std::operator==<char, std::char_traits<char>, std::allocator<char> > (
    __lhs=<error reading variable: Cannot access memory at address 0x10>, 
    __rhs=0x55555556de3c "T") at /usr/include/c++/7/bits/basic_string.h:6045
#2  0x000055555555c973 in Executive::askForPowerUp[abi:cxx11](int) (
    this=0x7fffffffe680, player=1) at Executive.cpp:865
#3  0x000055555555b827 in Executive::handleTurn (this=0x7fffffffe680, 
    player=1, AI=false) at Executive.cpp:742
#4  0x000055555555be58 in Executive::gameplay (this=0x7fffffffe680, AI=false)
    at Executive.cpp:797
#5  0x000055555555ade0 in Executive::run (this=0x7fffffffe680)
    at Executive.cpp:579
#6  0x000055555555742c in main (argc=1, argv=0x7fffffffe938) at main.cpp:23
